<a href="https://colab.research.google.com/github/QuanRy/TPR_L4/blob/main/lab4_TPR_NumPy_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Задание по библиотеке NumPy**

Скачаем и просмотрим версию установленной библиотеки NumPy

In [1]:

import numpy as np

print(np.__version__)

1.26.4


Заполним матрицу M

In [2]:
size = 85

M = 2 * np.ones((size, size), dtype=int)
np.fill_diagonal(M, 2 * np.arange(size) + 3)
print('M =\n', M)

M =
 [[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]



Заполнение матрицы N:

In [3]:
N = np.zeros((size, size), dtype=int)

# Четные строки
N[::2, :] = 4
N[::2, 2::3] = 5

# Нечетные строки
N[1::2, :] = 4
N[1::2, 1::2] = 7

print('N =\n', N)

N =
 [[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]


Вычисление вектора p:

In [4]:
p = 1 + np.random.normal(loc=2, scale=2, size=size) # (стандартное отклонение)
print('p =', p)

p = [ 0.21048402 -0.05519026  2.00063836  3.1126535   0.58436661  0.49484747
  2.33339703  4.36735096  6.07149655  3.17584096  0.09031041  1.28899955
  0.62807759  4.18201629  4.47189868  4.77858302  1.66723913  0.85956243
  3.57272713  3.38775357  2.61211426  1.5339628  -0.86409218  4.76669118
 -0.03710382  5.01543254  4.09005499 -0.40957942  1.57293888  4.74250679
  0.43066414  0.67543393  3.15846304  5.97913382  5.23969066  5.83544216
  2.21082961  3.16374504  0.75008436  4.88710653  2.42970615  3.26899215
  1.55567797  2.26060128  6.51631724  1.77210769  4.01516895  1.54180533
  3.71117988  4.54598378  4.99088406  5.72632141  4.05104567  5.60426352
  2.37900359  5.60204488  4.55183556  2.26611473  3.07662803 -1.2437355
  4.56553937  2.92010651  3.39593078  0.93280594  4.59448623  3.61526294
  2.9046215   3.19652671  1.22710872  3.61283906  2.25789997 -0.20361466
  1.37631297  5.29575273  2.58807541  5.19593945  5.40445514  4.05330475
  3.68506345  3.60906529 -1.24272164  4.70618564


Вычисление вектора q:

In [5]:
qT = np.multiply(N[24, :size], N[71, :size])
q = qT.T
print('q =', q)

q = [16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16]


Вычисление f

In [13]:
# Шаг 1: Вычисление g
M_submatrix = M[24:70, 13:28]  # Извлекаем подматрицу M для индексов от 24 до 69 и от 13 до 27
p_subvector = p[13:28]  # Извлекаем подмассив p для индексов от 13 до 27

# Вычисляем (7 * 10^(-6) * M * p)^2 и суммируем по всем элементам
g = np.sum(((const * M_submatrix * p_subvector)**2).prod(axis=1))

# Шаг 2: Вычисление f
q_squared = q**2  # Возводим в квадрат
k_star = np.argmax(q_squared)  # Находим индекс k*, для которого q_k^2 максимален
f = 4 * N[k_star, k_star]

# Результаты
print(f"Результат вычисления g: {g:.2f}")
print(f"Результат вычисления f: {f}")

Результат вычисления g: 0.00
Результат вычисления f: 28
